[package]
name = "kvs"
version = "0.0.1"
authors = ["Otavio Carvalho <otaviio@gmail.com>"]
descrition = "A simple key-value store"
edition = "2018"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
